services:

  # listens to mqtt packets and saves to database
  meshtastic-mqtt:
    container_name: meshtastic-mqtt
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /app/docker/mqtt.sh
    environment:
      DATABASE_URL: "mysql://root:password@database:3306/meshtastic-map?connection_limit=1000"
      MQTT_OPTS: ""  # add any custom mqtt.js options here

  # runs the web map ui
  meshtastic-map:
    container_name: meshtastic-map
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /app/docker/map.sh
    ports:
      - 8085:8085/tcp
    environment:
      DATABASE_URL: "mysql://root:password@database:3306/meshtastic-map?connection_limit=100"
      MAP_OPTS: "" # add any custom index.js options here

  # runs the database to store everything from mqtt
  database:
    container_name: database
    image: mysql:8.0
    ports:
      - 3306:3306/tcp
    environment:
      MYSQL_DATABASE: "meshtastic-map"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  database_data:

